"""empty message

Revision ID: 0eeee9fba54a
Revises: f41b6944ab67
Create Date: 2026-01-20 17:45:29.315435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '0eeee9fba54a'
down_revision: Union[str, Sequence[str], None] = 'f41b6944ab67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gear', schema=None) as batch_op:
        batch_op.add_column(sa.Column('m_t', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('d', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gear', schema=None) as batch_op:
        batch_op.drop_column('d')
        batch_op.drop_column('m_t')

    # ### end Alembic commands ###
