"""empty message

Revision ID: f41b6944ab67
Revises: 
Create Date: 2026-01-20 17:33:52.750871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f41b6944ab67'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gear',
    sa.Column('gear_id', sa.Integer(), nullable=False),
    sa.Column('m_n', sa.Float(), nullable=False),
    sa.Column('z', sa.Integer(), nullable=False),
    sa.Column('alpha_n', sa.Float(), nullable=False),
    sa.Column('beta', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('gear_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gear')
    # ### end Alembic commands ###
